name: Build Procomic
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Force Build
        run: |
          chmod +x gradlew
          mkdir -p src/ar/procomic/build
          ./gradlew :src:ar:procomic:assembleDebug -x spotlessCheck -x spotlessKotlinCheck
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Procomic-APK
          path: "**/*.apk"

